#!/usr/bin/env python3
"""
7_grinberg/README.md: Remove English sections, expand Korean content.
"""

path = 'C:\\test\\7_grinberg\\README.md'

with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

# ============================================================
# 1. Opening: bilingual headers -> Korean-only
# ============================================================

text = text.replace(
    '## Who Was He? (그는 누구인가)',
    '## 그는 누구인가'
)
text = text.replace(
    '## Overview of Syntergic Theory (신터지아 이론 개요)',
    '## 신터지아 이론 개요'
)
text = text.replace(
    '### The Core Equation (핵심 공식)',
    '### 핵심 공식'
)

# Remove duplicate English paragraph about disappearance (lines 9-11)
# English: "On **December 8, 1994**, ... unsolved."
text = text.replace(
    '''On **December 8, 1994**, days before his 48th birthday, Grinberg walked out of his home and vanished without a trace. His laboratory was found completely empty — all research data, equipment, notes, and experimental records gone. His disappearance remains unsolved.

---
''',
    '''---
'''
)

# ============================================================
# 2. Bilingual table -> Korean-only with expanded Korean content
# ============================================================

text = text.replace(
    '''| English | 한국어 | Meaning |
|---------|--------|---------|
| Syntergy (Sintergia) | 신터지아 (신테르기아) | 내적 응집성, 조직화, 정보 통합의 정도 |
| Neuronal Field | 신경장 (캄포 네우로날) | 뇌 신경 활동이 생성하는 에너지장으로 두개골 너머까지 확장 |
| Quantum Field / Lattice | 양자장 / 격자 (라티스) | 시공간의 근본 에너지 조직망, 모든 정보를 홀로그래픽으로 포함 |
| Hyperfield (Hipercampo) | 초장 (하이퍼캄포) | 모든 개별 신경장의 상호작용장, 집단 의식의 물질적 토대 |
| Directionality Factor | 방향성 인자 | 의식을 특정 경험 위치에 초점 맞추는 메커니즘 |
| Central Processor | 중앙 처리자 | 경험을 의식으로 변환하는 주체, 공간/시간 초월 |
| Observer | 관찰자 | 경험과 동일시되지 않는 순수 의식 주체 |
| Inclusion Principle | 포함 원리 | 각 수준이 상위/하위 수준의 정보를 포함하는 계층 구조 |
| Unity Consciousness | 통일 의식 | 신경장이 양자장의 기본 구조와 일치할 때 발생하는 최고 의식 상태 |''',
    '''| 용어 (한국어) | 영문 | 의미 |
|--------------|------|------|
| 신터지아 (Syntergy) | Sintergia | 시스템의 내적 응집성, 조직화, 정보 통합의 척도. 높은 신터지아 → 높은 포함성 → 의식 출현 |
| 신경장 (Neuronal Field) | Campo Neuronal | 뇌 신경 활동이 생성하는 에너지장으로 두개골 너머까지 확장. 뇌 상태, 기억, 지각의 형태 정보를 부호화 |
| 양자장/격자 (Lattice) | Campo Cuántico / Entramado | 시공간의 근본 에너지 조직망. 모든 정보를 홀로그래픽으로 포함하는 구조화된 정보 매트릭스 |
| 초장 (Hyperfield) | Hipercampo | 모든 개별 신경장의 상호작용장. 개인 의식을 넘어선 집단 의식의 물질적 토대. 행성 의식의 신경생리학적 기반 |
| 방향성 인자 | Factor de Direccionalidad | 의식을 특정 경험 위치에 초점 맞추는 메커니즘. 주의(attention)의 물리적 기제 |
| 중앙 처리자 | Procesador Central | 경험의 에너지 구조를 의식적 경험으로 변환하는 주체. 공간과 시간을 초월하며 동양 전통의 Atman, Purusha, 관찰자와 동일시됨 |
| 관찰자 | Observador | 경험과 동일시되지 않는 순수 의식 주체. 중앙 처리자의 또 다른 측면 |
| 포함 원리 | Principio de Inclusión | 각 수준이 상위/하위 수준의 정보를 포함하는 계층 구조. 신터지아 이론의 핵심 조직 원리 |
| 통일 의식 | Conciencia de Unidad | 신경장이 양자장의 기본 구조(완전 응집성)와 일치할 때 발생하는 최고 의식 상태. 동양 전통의 삼매/사마디에 해당 |'''
)

# ============================================================
# 3. Book 1: La Teoría Sintérgica (lines ~62-100)
# ============================================================

text = text.replace(
    '''**Main Thesis:** Consciousness and physical reality are two poles of a unified informational continuum called **Syntergy (Sintergia)**. Experience is not generated *by* the brain alone but emerges from the **interaction** between two fields.

**핵심 주제:** 의식과 물리적 현실은 **신터지아(Sintergia)** 라는 통합된 정보 연속체의 두 극이다. 경험은 뇌만이 아니라 두 장(field)의 상호작용에서 발생한다.

**The Core Equation:**
> **Experience (경험) = Neuronal Field (신경장) × Quantum Field (양자장)**

**Key Concepts (영문):**
- **Syntergy:** Degree of internal coherence, organization, and informational integration of a system. High syntergy → high inclusion → emergence of consciousness.
- **Neuronal Field:** Electromagnetic/energetic field generated by neural activity extending beyond the skull. Morphology encodes brain state, memory, and perception.
- **Quantum Field (Lattice):** Fundamental energetic organization of space-time — a structured informational matrix.
- **Experience = Neuronal Field × Quantum Field:** Interaction creates interference pattern decoded as qualia.
- **Syntergic Communication:** Under high syntergy, neuronal fields from different brains interact directly, enabling telepathy and non-local effects.
- **Inclusion Principle:** Complex systems organize hierarchically — each level contains info about higher and lower levels.
- **Gravitational Modification:** High-syntergy brains can alter local gravitational fields.

**Experiments/Evidence:**
- EEG coherence studies correlating high inter/intra-hemispheric coherence with syntergic states
- Faraday cage communication experiments showing information transfer correlated with EEG syntergy
- Weight reduction experiments on objects in shielded chambers

**Author's Conclusions:**
- Consciousness is not reducible to neural activity; it is a field phenomenon
- Reality is a co-creation between the observer and the observed
- The universe is a unified informational continuum where mind and matter converge

**핵심 개념 (한국어):**''',
    '''**핵심 주제:** 의식과 물리적 현실은 **신터지아(Sintergia)** 라는 통합된 정보 연속체의 두 극이다. 경험은 뇌만이 아니라 두 장(field) — 신경장(Neuronal Field)과 양자장(Quantum Field/Lattice) — 의 상호작용에서 발생한다. Grinberg는 의식이 신경 활동으로 환원될 수 없는 장(field) 현상이며, 현실은 관찰자와 관찰 대상의 공동 창조물이라고 주장한다. 우주는 마음과 물질이 수렴하는 통합된 정보 연속체이다.

**핵심 공식:**
> **경험 = 신경장 × 양자장**

**핵심 개념 (한국어, 상세):**
- **신터지아(Syntergy)**: 시스템의 내적 응집성, 조직화, 정보 통합의 척도. 높은 신터지아 → 높은 포함성 → 의식의 출현. 이 개념은 물리적 엔트로피의 반대 개념으로 이해할 수 있다.
- **신경장(Neuronal Field)**: 뉴런 활동이 생성하는 전자기적/에너지장. 두개골 너머 주변 공간으로 확장되며, 뇌 상태, 기억, 지각의 형태 정보(morphology)를 부호화한다.
- **양자장/라티스(Quantum Field/Lattice)**: 시공간의 근본적 에너지 조직. 모든 정보를 홀로그래픽으로 포함하는 구조화된 정보 매트릭스. Grinberg가 '실제로 발견한 것' 중 하나.
- **경험 = 신경장 × 양자장**: 두 장의 간섭 패턴(interference pattern)이 퀄리아(qualia)로 해독되어 경험을 창조한다.
- **신터지아 통신(Syntergic Communication)**: 고신터지아 상태에서 서로 다른 뇌의 신경장이 직접 상호작용하여 텔레파시 및 비국소적 효과가 가능해진다.
- **포함 원리(Inclusion Principle)**: 복잡한 시스템은 계층적으로 조직되며, 각 수준은 상위 및 하위 수준의 정보를 포함한다.
- **중력 변화(Gravitational Modification)**: 고신터지아 상태의 뇌는 국소 중력장을 변화시킬 수 있다. 차폐된 실험실에서 물체 무게 감소 실험으로 입증됨.

**실험 및 증거:**
- EEG 응집성 연구: 높은 좌/우반구 간 및 반구 내 응집성과 신터지아 상태의 상관관계 입증
- 패러데이 케이지(Faraday cage) 통신 실험: EEG 신터지아와 상관된 정보 전달 현상 확인
- 차폐된 실험실 내 물체 무게 감소 실험: 고신터지아가 중력에 미치는 영향 측정

**저자의 결론:**'''
)

# ============================================================
# 4. Book 2: El Cerebro Consciente (lines ~104-140)
# ============================================================

text = text.replace(
    '''**Main Thesis:** Consciousness is the result of the brain operating in a state of high **neurosyntergy** — when neural activity achieves sufficient coherence, inclusiveness, and integration, consciousness emerges as a self-referential property of the system.

**핵심 주제:** 의식은 뇌가 높은 **신경신터지아(neurosyntergy)** 상태에서 작동할 때 나타난다 — 신경 활동이 충분한 응집성, 포괄성, 통합성을 달성하면 의식이 시스템의 자기-지시적(self-referential) 속성으로 출현한다.

**Key Concepts:**
- **Neurosyntergy:** Neural systems along a continuum from low syntergy (fragmented, local) to high syntergy (global coherence). Consciousness appears above a threshold.
- **Self-reference:** Brain algorithmically includes itself in its own processing → self-awareness
- **Convergence-Divergence Theory:** Neural info converges into high-order inclusive algorithms then diverges back into specific responses
- **Central Processor:** Higher-order neural algorithms integrating all sensory/cognitive info into a unified experiential field
- **Present Expansion (Expansión del Presente):** Under high syntergy, subjective "present moment" expands, allowing access to normally unconscious micro-processes
- **Experience-Consciousness Identity:** When conscious awareness and experience become identical → access to the Ser (Being)

**핵심 개념 (한국어):**
- **신경신터지아(Neurosyntergy)**: 신경계는 저신터지아(분절된 국소 처리)에서 고신터지아(전역 응집)까지 연속체를 따라 작동
- **자기-지시(Self-reference)**: 뇌가 자신의 처리 과정에 스스로를 포함시키는 알고리즘 → 자의식
- **수렴-발산 이론**: 정보가 고차 포괄적 알고리즘으로 수렴된 후 특정 반응으로 발산
- **현재 확장(Expansión del Presente)**: 고신터지아 상태에서 주관적 "현재"가 확장되어 무의식적 미세 과정에 접근 가능

**Experiments/Evidence:**
- EEG studies showing coherence patterns correlate with conscious states
- Evoked potentials and concept formation experiments
- Split-brain studies reinterpreted through syntergic lens

**Author's Conclusions:**
- The brain is a "syntergic organ" — its purpose is to create increasingly inclusive, coherent states
- Consciousness is an emergent property of high neural organization that extends beyond the brain through the neuronal field
- Self-awareness = the brain's algorithm containing itself
- Healing and expanded perception are attainable through training syntergy (meditation, self-inquiry)

**저자의 결론 (한국어):**''',
    '''**핵심 주제:** 의식은 뇌가 높은 **신경신터지아(neurosyntergy)** 상태에서 작동할 때 나타난다. 신경 활동이 충분한 응집성(coherence), 포괄성(inclusiveness), 통합성(integration)을 달성하면 의식이 시스템의 자기-지시적(self-referential) 속성으로 출현한다. Grinberg는 뇌를 "신터지아 기관" — 더 포괄적이고 응집된 상태를 창조하는 것이 목적인 기관 — 으로 정의한다. 의식은 높은 신경 조직화의 창발적 속성이지만 신경장을 통해 뇌를 넘어 확장된다. 자의식은 뇌가 자신을 포함하는 알고리즘(self-reference)이다.

**핵심 개념 (한국어, 상세):**
- **신경신터지아(Neurosyntergy)**: 신경계는 저신터지아(분절된 국소 처리)에서 고신터지아(전역 응집)까지 연속체를 따라 작동한다. 의식은 특정 임계값 이상에서 나타난다. EEG 연구는 높은 응집성 패턴이 의식 상태와 상관관계가 있음을 보여준다.
- **자기-지시(Self-reference)**: 뇌가 자신의 처리 과정에 스스로를 포함시키는 알고리즘. 이것이 자의식(self-awareness)의 근본 메커니즘이다.
- **수렴-발산 이론(Convergence-Divergence)**: 신경 정보가 고차 포괄적 알고리즘(convergence)으로 수렴된 후 특정 반응(divergence)으로 발산되는 과정. 이는 뇌가 정보를 계층적으로 처리하는 방식을 설명한다.
- **중앙 처리자(Central Processor)**: 모든 감각/인지 정보를 통합된 경험장(unified experiential field)으로 통합하는 고차 신경 알고리즘. Grinberg는これを 동양 전통의 Atman, Purusha와 동일시한다.
- **현재 확장(Expansión del Presente)**: 고신터지아 상태에서 주관적 "현재"가 확장되어 평소에는 무의식적인 미세 과정(마이크로 프로세스)에 접근할 수 있게 된다. 시간 지각 자체가 변화하는 현상.
- **경험-의식 동일성(Experience-Consciousness Identity)**: 의식적 자각(conscious awareness)과 경험(experience)이 동일해지는 상태 — 존재(Ser)에 접근하는 문.

**실험 및 증거:**
- EEG 응집성 패턴과 의식 상태의 상관관계 연구
- 유발 전위(evoked potentials)와 개념 형성(concept formation) 실험
- 분할 뇌(split-brain) 연구를 신터지아 관점에서 재해석
- 명상과 자기 탐구(self-inquiry)를 통한 신터지아 훈련이 치유와 확장된 지각을 가능하게 함

**저자의 결론:**'''
)

# ============================================================
# 5. Book 3: Los Fundamentos de la Experiencia (lines ~143-179)
# ============================================================

text = text.replace(
    '''**Main Thesis:** Experience is a **creation** — not a passive reception of external stimuli. The book systematically deconstructs naive realism and builds a psychophysiological model of how the brain constructs experiential reality.

**핵심 주제:** 경험은 **창조**이다 — 외부 자극의 수동적 수용이 아니다. 이 책은 순진한 실재론을 체계적으로 해체하고 뇌가 경험적 현실을 구축하는 방법의 정신생리학적 모델을 구축한다.

**Key Concepts:**
- **Experience as Creation:** Every percept, emotion, thought is actively constructed by the brain's interaction with the quantum field
- **Algorithmic Model of Perception:** Brain operates through hierarchical algorithms — sensory input is structured into objects, concepts, meanings through convergence
- **The Quantum Brain:** Brain function involves quantum-level coherence, not purely classical
- **Perceptual Transparency:** Space appears empty but is a solid energetic continuum
- **Self as Algorithmic Convergence:** The sense of self (Yo) is the highest convergence point — the most inclusive pattern
- **Pathology as Low Syntergy:** Mental illness, dissociation, fragmentation = states of low neural coherence

**핵심 개념 (한국어):**
- **경험은 창조**: 모든 지각, 감정, 생각은 뇌와 양자장의 상호작용에 의해 능동적으로 구성됨
- **지각의 알고리즘 모델**: 뇌는 계층적 알고리즘을 통해 감각 입력을 객체→개념→의미로 구조화
- **양자 뇌**: 뇌 기능은 순수 고전적이지 않고 양자 수준의 응집성을 포함
- **지각적 투명성**: 공간은 비어 보이지만 실제로는 단단한 에너지 연속체
- **자아는 알고리즘 수렴**: 자아(Yo)는 가장 높은 수렴 지점 — 가장 포괄적인 패턴
- **병리는 저신터지아**: 정신 질환, 해리, 분열은 낮은 신경 응집성의 상태

**Experiments/Evidence:**
- Psychophysiological experiments on perception, memory, concept formation
- Sensory deprivation, meditation, and altered state studies
- Classical perception experiments reinterpreted through syntergic lens

**Author's Conclusions:**
- Reality is not given — it is a continuous creation
- Knowledge of this creative process is liberating: one can learn to "create reality" consciously
- The path to liberation is recognizing oneself as the creator of one's own experience

**저자의 결론 (한국어):**''',
    '''**핵심 주제:** 경험은 **창조**이다 — 외부 자극의 수동적 수용이 아니다. 이 책은 순진한 실재론(naive realism) — 즉 "현실이 우리가 지각하는 그대로 존재한다"는 믿음 — 을 체계적으로 해체하고, 뇌가 경험적 현실을 구축하는 정신생리학적 모델을 구축한다. Grinberg의 핵심 주장: 현실은 주어지는 것이 아니라 지속적인 창조물이며, 이 창조 과정에 대한 지식은 해방을 가져온다 — 의식적으로 "현실을 창조하는" 법을 배울 수 있다는 것이다.

**핵심 개념 (한국어, 상세):**
- **경험은 창조(Experience as Creation)**: 모든 지각(percept), 감정(emotion), 생각(thought)은 뇌와 양자장의 상호작용에 의해 능동적으로 구성된다. 외부에 미리 존재하는 "현실"을 단순히 수동적으로 받아들이는 것이 아니다.
- **지각의 알고리즘 모델(Algorithmic Model of Perception)**: 뇌는 계층적 알고리즘(hierarchical algorithms)을 통해 감각 입력을 객체(objects) → 개념(concepts) → 의미(meanings)로 구조화한다. 수렴(convergence) 과정을 통해 점점 더 추상적인 수준으로 정보가 통합된다.
- **양자 뇌(Quantum Brain)**: 뇌 기능은 순수 고전적(신경 자극의 단순한 전달)이지 않으며, 양자 수준의 응집성(quantum-level coherence)을 포함한다. 이는 신경 활동이 단순한 화학적/전기적 과정을 넘어선다는 의미다.
- **지각적 투명성(Perceptual Transparency)**: 공간은 비어 있는 것처럼 보이지만 실제로는 단단한 에너지 연속체(solid energetic continuum)이다. 우리가 '빈 공간'이라고 인식하는 것은 지각의 한계일 뿐이다.
- **자아는 알고리즘 수렴(Self as Algorithmic Convergence)**: 자아(Yo/Self)는 가장 높은 수렴 지점 — 뇌 정보 처리 시스템에서 가장 포괄적인 패턴이다. 독립적 실체가 아니라 정보 통합의 결과물이다.
- **병리는 저신터지아(Pathology as Low Syntergy)**: 정신 질환, 해리(dissociation), 분열(fragmentation)은 모두 낮은 신경 응집성(low neural coherence)의 상태로 설명된다. 즉, 정신 건강은 뇌의 정보 통합 능력과 직접 연결된다.

**실험 및 증거:**
- 지각, 기억, 개념 형성에 관한 정신생리학적 실험들
- 감각 차단(sensory deprivation), 명상, 변성 의식 상태(altered state) 연구
- 고전적 지각 실험(예: 착시 현상)을 신터지아 관점에서 재해석

**저자의 결론:**'''
)

# ============================================================
# 6. Book 4: La Luz Angelmática (lines ~182-222)
# ============================================================

text = text.replace(
    '''**Main Thesis:** Grinberg's most personal and mystical book — a blend of autobiographical narrative and experimental report on extraocular vision. It describes spiritual journeys and reflections on consciousness, being, time, and the "angelmatic light" — the light of consciousness witnessing itself.

**핵심 주제:** Grinberg의 가장 개인적이고 신비적인 책 — 자전적 내러티브와 초시각 실험 보고서의 혼합. 의식, 존재, 시간, 그리고 "안젤마틱 빛"(의식이 자신을 목격하는 빛)에 대한 철학적 성찰을 담고 있다.

**Key Concepts:**
- **Luz Angelmática (Angelmátic Light):** Meta-awareness — the light of consciousness itself; connection between individual consciousness and the "above" (true identity)
- **Ser (Being):** Pure existence without content; independent, non-local, absolute freedom, pure love
- **Expansion of Time / Lentificación:** Accessing unconscious processes by slowing subjective time
- **Consciousness of Consciousness:** Metacognition — witnessing the witness
- **Ego Expansion:** True way to dissolve ego — expand it until it encompasses everything, then ego disappears because all is One
- **Intuition:** Direct contact with information in the energetic organization of space

**Extraocular Vision Experiment (Appendix I):**
- 19 children (ages 5–13) trained to see without eyes
- Protocol: breathing → "Who am I?" meditation → energy visualization → blindfolded viewing
- Results: reading, color description, internal organ perception, diagnosis, healing
- Quartz crystal dramatically enhanced extraocular vision
- Vision was omnidirectional (could see behind)
- Age limit: difficult after ~15 years
- Appeared all-at-once (quantum leap)

**Author's Conclusions:**
- The "angelmatic light" is the ultimate goal: permanent ecstasy through recognition of oneself as creator of experience
- Extraocular vision confirms Syntergic Theory — perception is field interaction, not sensory processing
- Children with strongest sense of self-identity learned fastest

**핵심 개념 (한국어):**
- **안젤마틱 빛(Luz Angelmática)**: 메타-자의식 — 의식 자체의 빛; 개인 의식과 "위"(참된 정체성)의 연결
- **존재(Ser)**: 내용 없는 순수 존재; 독립적, 비국소적, 절대 자유, 순수한 사랑
- **시간 확장/느려짐**: 주관적 시간을 늦춰 무의식 과정에 접근
- **의식의 의식**: 메타인지 — 목격자를 목격함
- **에고 확장**: 에고를 해체하는 진정한 방법은 전체를 포용할 때까지 확장하는 것 — 하나가 되면 에고는 사라진다
- **직관**: 공간의 에너지 조직에 포함된 정보와의 직접 접촉

**저자의 결론 (한국어):**
- 안젤마틱 빛이 궁극적 목표: 자신을 경험의 창조자로 인식함으로써 영원한 황홀경
- 초시각은 신터지아 이론을 확인 — 지각은 장(field) 상호작용이지 감각 처리가 아니다
- 가장 강한 자의식을 가진 아이들이 가장 빨리 학습했다''',
    '''**핵심 주제:** Grinberg의 가장 개인적이고 신비적인 책 — 자전적 내러티브와 초시각(extraocular vision) 실험 보고서의 혼합이다. 의식, 존재, 시간, 그리고 "안젤마틱 빛"(의식이 자신을 목격하는 빛)에 대한 철학적 성찰을 담고 있다. 안젤마틱 빛이 궁극적 목표이며, 자신을 경험의 창조자로 인식함으로써 영원한 황홀경(permanent ecstasy)에 도달하는 것이 이 책이 제시하는 길이다.

**핵심 개념 (한국어, 상세):**
- **안젤마틱 빛(Luz Angelmática / Angelmátic Light)**: 메타-자의식(meta-awareness) — 의식 자체의 빛. 개인 의식과 "위"(참된 정체성)의 연결 지점. 단순한 시각적 경험이 아니라 존재 자체의 본질을 드러내는 빛이다.
- **존재(Ser / Being)**: 내용 없는 순수 존재(pure existence without content). 독립적, 비국소적, 절대 자유, 순수한 사랑. 동양 전통의 순수 의식(pure consciousness) 개념과 일치한다.
- **시간 확장/느려짐(Lentificación / Expansion of Time)**: 주관적 시간을 늦춰 평소에는 의식에 접근할 수 없는 무의식적 과정(무의식의 미세 과정)에 접근하는 현상. 이는 명상 수행이 깊어질수록 자연스럽게 나타난다.
- **의식의 의식(Consciousness of Consciousness)**: 메타인지(metacognition) — 목격자를 목격하는 능력. 즉, "내가 지금 보고 있다"는 사실을 아는 차원을 넘어, 그 "보는 자" 자체를 의식하는 상태.
- **에고 확장(Ego Expansion)**: 에고를 해체하는 진정한 방법은 그것을 억압하거나 부정하는 것이 아니라, 전체를 포용할 때까지 확장하는 것이다. 모든 것이 하나(One)가 되면 에고는 자연스럽게 사라진다.
- **직관(Intuition)**: 공간의 에너지 조직(energy organization of space / lattice)에 포함된 정보와의 직접 접촉. 개념이나 추론을 거치지 않은 직접적 앎.

**초시각 실험 (부록 I):**
- 19명의 어린이(5-13세)가 눈을 사용하지 않고 보는 법을 훈련받음
- 훈련 프로토콜: 호흡 운동 → "나는 누구인가?" 명상 → 에너지 시각화 → 안대 착용 후 보기
- 결과: 글자 읽기, 색상 식별, 내부 장기 인지, 질병 진단, 치유까지 가능
- 수정(Quartz Crystal)을 쥐면 초시각이 현저히 향상됨
- 시야는 전방위적(omnidirectional) — 뒤도 볼 수 있음
- 15세 이후에는 현상 유도가 어려움
- 초시각은 항상 갑자기 나타남 (양자적 도약) — 전혀 안 보임 → 거의 완벽한 디코딩으로 순간적 전환
- 초시각은 신터지아 이론을 확인 — 지각은 장(field) 상호작용이지 감각 처리가 아니다
- 가장 강한 자의식(self-identity)을 가진 아이들이 가장 빨리 학습했다

**저자의 결론:**'''
)

# ============================================================
# 7. Ending sections: English -> Korean
# ============================================================

# Table header line
text = text.replace(
    '### Complete Book Table (전체 책 목록)',
    '### 전체 책 목록'
)
text = text.replace(
    'All 39 books downloaded from jacobogrinberg.org (PDF format, 423 MB total).\n26 have extractable text. 13 are scanned images requiring OCR.\n2 books (La Batalla por el Templo, La Expansión del Presente) listed on site but no download link available.',
    'jacobogrinberg.org에서 총 39권 PDF 다운로드 완료 (423 MB). 26권 텍스트 추출 가능, 13권 스캔 이미지(OCR 필요). 2권(La Batalla por el Templo, La Expansión del Presente)은 사이트에 목록만 있고 다운로드 불가.'
)

# Table header row
text = text.replace(
    '| # | Title | Pages | Size | Text | Section |',
    '| # | 제목 | 페이지 | 크기 | 텍스트 | 구분 |'
)

# Key Differences section
text = text.replace(
    '### Key Differences Between Books (책 간 주요 차이)',
    '### 책 간 주요 차이점'
)
text = text.replace(
    '**Theoretical Works (텍스트 추출 완료):**',
    '**이론서 (텍스트 추출 완료):**'
)
text = text.replace(
    '**Experimental Works (기술적 차단):**',
    '**실험서 (기술적 문제로 미추출):**'
)
text = text.replace(
    '**Ethnographic Works (텍스트 추출 완료):**',
    '**민족지/샤먼 연구 (텍스트 추출 완료):**'
)

# Bibliography section
text = text.replace(
    '''### Bibliography (참고 자료)

- **jacobogrinberg.org** — Full collection of 39 downloadable PDFs
- **UNAM (Universidad Nacional Autónoma de México)** — Where Grinberg conducted his research
- **National Institute for the Study of Consciousness** — Founded by Grinberg
- Documentary: "The Secret of Dr. Grinberg" (Netflix-style)''',
    '''### 참고 자료

- **jacobogrinberg.org** — Grinberg 저작 39권 PDF 전체 컬렉션
- **UNAM (멕시코 국립자치대학교)** — Grinberg가 연구를 수행한 기관
- **국립의식연구소 (National Institute for the Study of Consciousness)** — Grinberg가 설립
- **다큐멘터리**: "The Secret of Dr. Grinberg" (Netflix 스타일) — 그의 실종과 연구에 관한 기록'''
)

# Bilingual footer
text = text.replace(
    '''*This is an objective collection of information about Jacobo Grinberg-Zylberbaum's work. Connections to other frameworks are left for future analysis.*

*이 문서는 Jacobo Grinberg-Zylberbaum의 작업에 관한 객관적 정보 모음입니다. 다른 프레임워크와의 연결은 향후 분석을 위해 남겨둡니다.*''',
    '''*이 문서는 Jacobo Grinberg-Zylberbaum(하코보 그린베르크-질버바움)의 작업에 관한 객관적 정보 모음입니다. 다른 세계관(매트릭스, 영지주의, 샤머니즘 등)과의 연결은 향후 분석을 위해 남겨둡니다.*
*현재까지 39권 PDF 확보, 26권 텍스트 추출 및 분석 완료. 추가 정보는 지속적으로 업데이트됩니다.*'''
)

# ============================================================
# 8. Section E/F headers: bilingual -> Korean
# ============================================================

text = text.replace(
    '### Section E: Poetry & Fiction (시와 소설)',
    '### Section E: 시와 소설'
)
text = text.replace(
    '### Section F: Books with Web Descriptions Only (웹 설명 기반)',
    '### Section F: 웹 설명 기반 (텍스트 미추출)'
)

# ============================================================
# Write output
# ============================================================

with open(path, 'w', encoding='utf-8') as f:
    f.write(text)

lines = text.count('\n') + 1
print(f'Done. {lines} lines written.')
