services:
  guacdb:
    container_name: guacamole-db
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'GuacPass123!'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: 'GuacPass123!'
    volumes:
      - guac-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  guacd:
    container_name: guacamole-guacd
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    depends_on:
      guacdb:
        condition: service_healthy

  guacamole:
    container_name: guacamole-web
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacdb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "GuacPass123!"
      WEBAPP_CONTEXT: "ROOT"
    depends_on:
      guacdb:
        condition: service_healthy
      guacd:
        condition: service_started

volumes:
  guac-db-data:
